app/home_receipt/models.py
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func
from app import db


Base = db.Model

class Project(Base):

    __tablename__ = 'project'

    id = sa.Column(sa.Integer(), autoincrement=True, primary_key=True)
    name = sa.Column(sa.String(64))
    created_at = sa.Column(sa.TIMESTAMP(), server_default=func.now())
    details = sa.Column(sa.Text())


class FilteredAddress(Base):

    __tablename__ = 'filtered_address'

    id = sa.Column(sa.Integer(), autoincrement=True, primary_key=True)
    address = sa.Column(sa.String(64))
    created_at = sa.Column(sa.TIMESTAMP(), server_default=func.now())
    details = sa.Column(sa.Text())


class Supplier(Base):

    __tablename__ = 'supplier'

    id = sa.Column(sa.Integer(), autoincrement=True, primary_key=True)
    name = sa.Column(sa.String(64))
    address = sa.Column(sa.String(128))
    postcode = sa.Column(sa.Integer())
    city = sa.Column(sa.String(64))
    email = sa.Column(sa.String(64))
    siret = sa.Column(sa.String(32))
    phone = sa.Column(sa.String(256))
    created_at = sa.Column(sa.TIMESTAMP(), server_default=func.now())
    details = sa.Column(sa.Text())


class Bill(Base):

    __tablename__ = 'bill'

    id = sa.Column(sa.Integer(), autoincrement=True, primary_key=True)
    amount = sa.Column(sa.Float())
    date = sa.Column(sa.TIMESTAMP(), server_default=func.now())
    dtn_end_amort = sa.Column(sa.TIMESTAMP(), server_default=func.now())
    file = sa.Column(sa.String(256))
    details = sa.Column(sa.Text())
    supplier_id = sa.Column(sa.Integer(), sa.ForeignKey('supplier.id'))
    project_id = sa.Column(sa.Integer(), sa.ForeignKey('project.id'))
    cat_id = sa.Column(sa.Integer(), sa.ForeignKey('categorie.id'))


class Categorie(Base):

    __tablename__ = 'categorie'

    id = sa.Column(sa.Integer(), autoincrement=True, primary_key=True)
    name = sa.Column(sa.String(64))
    created_at = sa.Column(sa.TIMESTAMP(), server_default=func.now())
    details = sa.Column(sa.Text())


class Revenue(Base):

    __tablename__ = 'revenue'

    id = sa.Column(sa.Integer(), autoincrement=True, primary_key=True)
    amount = sa.Column(sa.Float())
    client_id = sa.Column(sa.Integer(), sa.ForeignKey('client.id'))
    project_id = sa.Column(sa.Integer(), sa.ForeignKey('project.id'))
    created_at = sa.Column(sa.TIMESTAMP(), server_default=func.now())
    details = sa.Column(sa.Text())


class Client(Base):

    __tablename__ = 'client'

    id = sa.Column(sa.Integer(), autoincrement=True, primary_key=True)
    name = sa.Column(sa.String(128))
    address = sa.Column(sa.String(128))
    postcode = sa.Column(sa.Integer())
    city = sa.Column(sa.String(64))
    phone = sa.Column(sa.String(32))
    created_at = sa.Column(sa.TIMESTAMP(), server_default=func.now())
    details = sa.Column(sa.Text())

app/home_receipt/__init__.py
# -*- encoding: utf-8 -*-

from flask import Blueprint

blueprint = Blueprint(
    'receipt_blueprint',
    __name__,
    url_prefix=''
)

app/home_receipt/routes.py
# -*- encoding: utf-8 -*-
from datetime import datetime

import dateutil.utils
import os
from app.home_receipt import blueprint
from flask import render_template, request, redirect, url_for, json, session
from app.home_receipt.models import *
import app.home_receipt.constants as ct
from app.home_receipt.doc_read import parse_bill
from wtforms import Form, StringField, validators, FloatField, IntegerField, SelectField, DateField, FileField

from flask_breadcrumbs import Breadcrumbs, register_breadcrumb
import app.home_receipt.breadcrumb as bc
import app.home_receipt.db_operations as op
from run import app


class AddProjectForm(Form):
    project_name = StringField('Product Name', [validators.DataRequired(), validators.Length(min=4, max=35)])

class AnalysisBillForm(Form):
    file_input = FileField("PDF file with bill details")
    supplier_select = StringField("Select Supplier", [validators.DataRequired()])

class BillForm(Form):
    supplier_select = SelectField("Select Supplier", [validators.DataRequired()])
    type_select = SelectField("Bill Type", [validators.DataRequired()])
    vat_price = FloatField("VAT Price", [validators.DataRequired(), validators.number_range(min=0)])
    date = DateField("Bill date", [validators.DataRequired()])
    supplier_name = StringField('Supplier name')
    supplier_address = StringField('Supplier address')
    supplier_postcode = IntegerField('Supplier postcode', [validators.number_range(min=0)])
    supplier_city = StringField('Supplier city')
    supplier_email = StringField('Supplier city')
    supplier_siret = StringField('Supplier SIRET')
    supplier_phone = StringField('Supplier phone')

class SettingsForm(Form):
    address = StringField("Address to exclude", [validators.DataRequired()])

@blueprint.app_template_filter('strftime')
def _jinja2_filter_datetime(date):
    return date.strftime("%d %B, %Y")


@blueprint.route('/')
def route_default():
    return redirect(url_for('receipt_blueprint.index'))

@blueprint.route('/index', methods=['GET', 'POST'])
@register_breadcrumb(blueprint, '.', 'Home')
def index():
    query_pj = Project.query.all()
    file_form = AnalysisBillForm(request.form)
    return render_template('home-receipt/receipts_table.html', title='Bootstrap Table', projects=query_pj,
                           sel_project=get_sel_project(), file_form=file_form)


@blueprint.route('/suppliers')
@register_breadcrumb(blueprint, '.suppliers', 'Suppliers')
def suppliers():
    query_pj = Project.query.all()
    query_suppliers = db.session.query(Supplier, func.count(Bill.id), func.sum(Bill.amount)).\
        join(Bill, Supplier.id == Bill.supplier_id). \
        filter(Bill.project_id == get_sel_project()).group_by(Supplier.id).all()
    return render_template('home-receipt/suppliers.html', title='Bootstrap Table', query=query_suppliers,
                           projects=query_pj, sel_project=get_sel_project())


@blueprint.route('/products')
@register_breadcrumb(blueprint, '.products', 'Products')
def products():
    return render_template('home-receipt/products_table.html', title='Bootstrap Table')


@blueprint.route('/project', methods=['GET', 'POST'])
def projects():
    query_pj = Project.query.all()
    form = AddProjectForm(request.form)
    if request.method == 'POST' and form.validate():
        project = Project(name=form.project_name.data)
        db.session.add(project)
        db.session.commit()
        return redirect(url_for('receipt_blueprint.projects'))
    else:
        query = Project.query
        return render_template('home-receipt/projects_table.html', title='Bootstrap Table', form=form,
                           query=query.all(), year=dateutil.utils.today().year, projects=query_pj,
                           sel_project=get_sel_project())


@blueprint.route('/project/del/<id_project>')
def del_project(id_project):
    Project.query.filter_by(id=id_project).delete()
    db.session.commit()
    return redirect(url_for('receipt_blueprint.projects'))


@blueprint.route('/project/sel/<id_project>')
def select_project(id_project):
    session[ct.SEL_PROJECT] = int(id_project)
    return redirect(url_for('receipt_blueprint.index'))

@blueprint.route('/settings', methods=['GET', 'POST'])
def settings():
    query_pj = Project.query.all()
    form = SettingsForm(request.form)
    addresses = FilteredAddress.query.all()
    if request.method == 'POST' and form.validate():
        address = FilteredAddress(address=form.address.data)
        db.session.add(address)
        db.session.commit()
        return redirect(url_for('receipt_blueprint.settings'))
    return render_template('home-receipt/settings.html', title='Bootstrap Table', form=form,
                           year=dateutil.utils.today().year, projects=query_pj,
                           sel_project=get_sel_project(), addresses=addresses)

@blueprint.route('/settings/del/<id_address>', methods=['GET'])
def del_settings(id_address):
    FilteredAddress.query.filter_by(id=id_address).delete()
    db.session.commit()
    return redirect(url_for('receipt_blueprint.settings'))


@blueprint.route('/bills', methods=['GET', 'POST'])
@register_breadcrumb(blueprint, '.bills', 'Bills')
def bills():
    query_pj = Project.query.all()
    query_bill = db.session.query(Bill, Supplier).join(Supplier, Supplier.id == Bill.supplier_id).\
        filter(Bill.project_id == get_sel_project()).all()
    pj = Project.query.filter_by(id=get_sel_project()).first()
    if pj is None:
        app.logger.info("No project found can't add a Bill")
        return redirect(url_for('receipt_blueprint.index'))
    form = AnalysisBillForm(request.form)
    if request.method == 'POST':
        pf_folder = ct.PJ_FOLDER.format(id=pj.id, name=pj.name)
        if not os.path.exists(pf_folder):
            os.makedirs(pf_folder)
        uploaded_file = request.files[form.file_input.name]
        uploaded_file.save(pf_folder + uploaded_file.filename)
        parse_bill(pf_folder + uploaded_file.filename, pj.id)
        return redirect(url_for('receipt_blueprint.bills'))
    return render_template('home-receipt/add_bill.html', title='Bootstrap Table', form=form,
                           year=dateutil.utils.today().year, projects=query_pj, bills=query_bill,
                           sel_project=get_sel_project())


@blueprint.route('/bill/<id_bill>', methods=['GET', 'POST'])
def bill_details(id_bill):
    query_pj = Project.query.all()
    bill = Bill.query.filter_by(id=id_bill).first()
    form = BillForm()
    if bill is not None:
        supplier = Supplier.query.filter_by(id=bill.supplier_id).first()
        all_suppliers = op.query2dicts(Supplier.query.all())
        if supplier is not None:
            form.vat_price.default = bill.amount
            form.date.default = bill.date
            form.supplier_select.choices = op.get_suppliers()
            form.supplier_select.default = bill.supplier_id
            form.type_select.choices = ct.BILL_TYPE_SELECT
            form.supplier_name.default = supplier.name
            form.supplier_city.default = supplier.city
            form.supplier_email.default = supplier.email
            form.supplier_phone.default = supplier.phone
            form.supplier_address.default = supplier.address
            form.supplier_postcode.default = supplier.postcode
            form.supplier_siret.default = supplier.siret
            form.process()
    return render_template('home-receipt/bill_details.html', title='Bootstrap Table',
                           year=dateutil.utils.today().year, projects=query_pj,
                           sel_project=get_sel_project(), bill=bill, form_bill=form, suppliers=all_suppliers)

@blueprint.route('/update_bill/<id_bill>', methods=['POST'])
def update_bill(id_bill):
    form = BillForm(request.form)
    bill = Bill.query.filter_by(id=id_bill).first()
    form.supplier_select.choices = op.get_suppliers()
    form.type_select.choices = ct.BILL_TYPE_SELECT
    if request.method == 'POST' and form.validate() and bill is not None:
        bill.amount = form.vat_price.data
        bill.date = form.date.data
        bill.supplier_id = form.supplier_select.data
        supplier = Supplier.query.filter_by(id=bill.supplier_id).first()
        if supplier is not None:
            supplier.siret = form.supplier_siret.data
            supplier.phone = form.supplier_phone.data
            supplier.name = form.supplier_name.data
            supplier.postcode = form.supplier_postcode.data
            supplier.address = form.supplier_address.data
            supplier.email = form.supplier_email.data
            supplier.city = form.supplier_city.data
        db.session.commit()
    return redirect(url_for('receipt_blueprint.bill_details', id_bill=id_bill))



@blueprint.route('/bill/del/<id_bill>', methods=['GET'])
def del_bill(id_bill):
    Bill.query.filter_by(id=id_bill).delete()
    db.session.commit()
    op.delete_ophan_supplier()
    return redirect(url_for('receipt_blueprint.bills'))


@blueprint.route('/receipt/del/<id_receipt>')
def receipt_delete(id_receipt):
    op.delete_receipt_and_paid_products(id_receipt)
    op.delete_orphan_shops()
    return redirect(url_for('receipt_blueprint.index'))


def get_sel_project():
    if ct.SEL_PROJECT in session and session[ct.SEL_PROJECT] is not None:
        sel_pj = Project.query.filter_by(id=session[ct.SEL_PROJECT]).first()
        if sel_pj is None:
            # Selected project deleted
            app.logger.info('Selected project deleted id={id}'.format(id=session[ct.SEL_PROJECT]))
            session[ct.SEL_PROJECT] = None
    else:
        sel_pj = Project.query.first()
        if sel_pj is None:
            session[ct.SEL_PROJECT] = None
        else:
            session[ct.SEL_PROJECT] = sel_pj.id
    return session[ct.SEL_PROJECT]

app/templates/home-receipt/add_bill.html
{% extends "base.html" %}
{% from "_formhelpers_add_product.html" import render_field %}
{% from "_formhelpers_update_receipt.html" import render_field_up %}

{% block content %}
<div class="border p-2 rounded-1 m-2">
    <form action="{{url_for('receipt_blueprint.bills')}}" method="post" enctype="multipart/form-data">
        <div class="row p-2 align-items-end">
            <div class="col-sm-4">
                <h5>Bill in PDF<i class="mx-1 bi bi-file-pdf"></i></h5>
                {{ render_field(form.file_input, class="form-control-file") }}
            </div>
            <div class="col-sm-2 ">
                <button type="submit" class="my-2 btn btn-primary ">
                    <i class="bi p-1 bi-eyeglasses"></i>
                    analysis</button>
            </div>
        </div>
    </form>
</div>
<table id="data_table" class="my-3 table table-striped">
    <thead>
      <tr>
          <th>Supplier</th>
          <th>Date</th>
          <th>Amount € (VAT inc.)</th>
          <th>Details</th>
          <th></th>
      </tr>
    </thead>
    <tbody>
      {% for bill, supplier in bills %}
          <tr>
            <td>{{ supplier.id }}-{{ supplier.name }}</td>
            <td>{{ bill.date }}</td>
            <td>{{ "%.2f €"|format(bill.amount) }}</td>
            <td>
              <a href="{{ url_for('receipt_blueprint.bill_details', id_bill=bill.id)}}"
                    class="btn btn-primary">
                <i class="mx-1 bi bi-zoom-in"></i> details
              </a>
            </td>
              <td>
                  <a id='del_{{bill.id}}'
                       href="{{ url_for('receipt_blueprint.del_bill', id_bill=bill.id)}}"
                       role="button" class="btn btn-outline-danger btn-sm">
                      <i class="bi bi-trash"></i></a>
              </td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

app/templates/home-receipt/bill_details.html
{% extends "base.html" %}
{% from "_formhelpers_add_product.html" import render_field %}
{% from "_formhelpers_update_receipt.html" import render_field_up %}

{% block content %}
<div class="border p-2 rounded-1 m-2">
    <form action="{{url_for('receipt_blueprint.update_bill', id_bill=bill.id)}}" method="post" enctype="multipart/form-data">
        <div class="row p-2 align-items-end">
                <h5>Bill Details<i class="mx-1 bi bi-file-pdf"></i></h5>
                <div class="container">
                <div class="row p-2">
                  <div class="col">
                    <div class="input-group">
                        <script>
                            var suppliers = {{ suppliers|tojson|safe }};
                        </script>
                      <span class="input-group-text" ><i class="mx-1 bi bi-shop"></i>Supplier</p></span>
                       {{ render_field_up(form_bill.supplier_select, class="form-select", onchange="refresh_supplier()") }}
                    </div>
                  </div>
                  <div class="col">
                    <div class="input-group flex-nowrap">
                      <span class="input-group-text" id="total-wrapping"><i class="bi bi-currency-euro"></i>Total</p></span>
                      {{ render_field_up(form_bill.vat_price, class="form-control") }}
                    </div>
                  </div>
                  <div class="col">
                    <div class="input-group flex-nowrap">
                      <span class="input-group-text" id="date-wrapping"><i class="px-1 bi bi-calendar3-event"></i>Date</p></span>
                      {{ render_field_up(form_bill.date, class="form-control") }}
                    </div>
                  </div>
                </div>
                <div class="row p-2">
                    <div class="col">
                    <div class="input-group">
                      <span class="input-group-text" ><i class="mx-1 bi bi-receipt"></i>Type</p></span>
                       {{ render_field_up(form_bill.type_select, class="form-select") }}
                    </div>
                  </div>
                </div>
          </div>
        </div>
        <div class="row p-2 align-items-end">
                <h5>Supplier Details<i class="mx-1 bi bi-file-pdf"></i></h5>
                <div class="container">
                <div class="row p-2">
                  <div class="col">
                    <div class="input-group">
                      <span class="input-group-text" ><i class="mx-1 bi bi-shop"></i>Supplier Name</p></span>
                       {{ render_field_up(form_bill.supplier_name, class="form-control") }}
                    </div>
                  </div>
                  <div class="col">
                    <div class="input-group flex-nowrap">
                      <span class="input-group-text"><i class="bi bi-currency-euro"></i>email</p></span>
                      {{ render_field_up(form_bill.supplier_email, class="form-control") }}
                    </div>
                  </div>
                  <div class="col">
                    <div class="input-group flex-nowrap">
                      <span class="input-group-text"><i class="px-1 bi bi-calendar3-event"></i>Phone</p></span>
                      {{ render_field_up(form_bill.supplier_phone, class="form-control") }}
                    </div>
                  </div>
                </div>
                <div class="row p-2">
                    <div class="col">
                    <div class="input-group">
                      <span class="input-group-text" ><i class="mx-1 bi bi-receipt"></i>Address</p></span>
                       {{ render_field_up(form_bill.supplier_address, class="form-control") }}
                    </div>
                  </div>
                    <div class="col">
                    <div class="input-group">
                      <span class="input-group-text" ><i class="mx-1 bi bi-receipt"></i>Post code</p></span>
                       {{ render_field_up(form_bill.supplier_postcode, class="form-control") }}
                    </div>
                  </div>
                    <div class="col">
                    <div class="input-group">
                      <span class="input-group-text" ><i class="mx-1 bi bi-receipt"></i>City</p></span>
                       {{ render_field_up(form_bill.supplier_city, class="form-control") }}
                    </div>
                  </div>
                </div>
                <div class="row p-2">
                    <button type="submit" class="btn btn-success btn-sm"><i class="bi p-1 bi-arrow-repeat"></i>Update</button>
                </div>
          </div>
        </div>
    </form>
</div>
<embed src="{{ bill.file }}" width=800 height=500 type='application/pdf'/>
{% endblock %}

app/templates/home-receipt/product_detail.html
{% extends "base.html" %}

{% block content %}

<script>
    var data = [{% for shop, paid_product, receipt, product_group in query %}
    "{{paid_product.unit_price}}",
    {% endfor %}];
    var labels = [{% for shop, paid_product, receipt, product_group in query %}
    "{{receipt.date}}",
    {% endfor %}];
    var databar = [{% for shop, price in queryshop %}
        "{{price}}",
    {% endfor %}];
    var labelsbar = [{% for shop, price in queryshop %}
        "{{shop}}",
    {% endfor %}];
</script>
<div class="container">
    <div class="row p-2">
        <div class="col px-2">
            <canvas id="linechart"></canvas>
        </div>
        <div class="col px-2">
            <canvas id="barchart"></canvas>
        </div>
    </div>
    <div class="row p-2">

    </div>
</div>
<script type="text/javascript" src="/static/linechart.js" language="javascript"></script>
<script type="text/javascript" src="/static/barchart.js" language="javascript"></script>
<div class="row p-2">
<table id="data_table" class="my-3 table table-striped">
    <thead>
      <tr>
        <th>Shop</th>
        <th>Date</th>
        <th>Unit Price</th>
        <th>Qty</th>
        <th>Price</th>
        <th>Linked Receipt</th>
      </tr>
    </thead>
    <tbody>
      {% for shop, paid_product, receipt, product_group in query %}
          <tr>
            <td>{{ shop.name }}</td>
            <td>{{ receipt.date }}</td>
            <td>{{ paid_product.unit_price }} €</td>
            <td>{{ paid_product.quantity }}</td>
            <td>{{ paid_product.price }} €</td>
            <td>
                <a href="{{ url_for('receipt_blueprint.receipt_detail', id_receipt=receipt.id)}}"
                    class="btn btn-primary">
                <i class="mx-1 bi bi-zoom-in"></i> receipt {{receipt.id}}
              </a>
            </td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="row my-4 p-2">
    <h6><strong>Aliases used for product</strong></h6>
    <table class="table table-striped">
        <thead>
            <th>Aliases</th>
            <th>Delete</th>
        </thead>
        <tbody>
            {% for product in queryalias %}
            <tr>
                <td>{{product.name}}</td>
                <td>
                    <a href="{{url_for('receipt_blueprint.alias_delete', id_alias=product.id)}}"
                       role="button" class="btn btn-outline-danger btn-sm">
                      <i class="bi bi-x-circle"></i></a>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/home-receipt/products_table.html
{% extends "base.html" %}

{% block content %}

<table id="data_table" class="my-3 table table-striped">
    <thead>
      <tr>
        <th>Product</th>
        <th>Nb buy</th>
        <th>Avg Price</th>
        <th>Min Price</th>
        <th>Max Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for product_group, count, avg, min, max in query %}
          <tr>
            <td>{{ product_group.name }}</td>
            <td>{{ count }}</td>
            <td>{{ "%.2f €"|format(avg) }}</td>
            <td>{{ "%.2f €"|format(min) }}</td>
            <td>{{ "%.2f €"|format(max) }}</td>
            <td>
              <a href="{{ url_for('receipt_blueprint.product_detail', id_product=product_group.id)}}"
                    class="btn btn-primary">
                <i class="mx-1 bi bi-zoom-in"></i> details
              </a></td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

app/templates/home-receipt/projects_table.html
{% extends "base.html" %}
{% from "_formhelpers_add_product.html" import render_field %}
{% from "_formhelpers_update_receipt.html" import render_field_up %}

{% block content %}
<div class="flex-shrink-0">
    <div class="p-2 mb-4 border border-light rounded">
        <h6>Manage Projects</h6>
        <form action="" method="post">
            <div class="row p-2">
                  <label class="col-sm-2 col-form-label">Project Name</label>
                  <div class="col-sm-6">
                      {{ render_field(form.project_name, class="form-control", placeholder="Gaujac") }}
                  </div>
                  <div class="col-sm-2">
                      <button type="submit" class="btn btn-success ">
                          <i class="bi p-1 bi-patch-plus-fill"></i>
                          Add</button>
                  </div>
            </div>
        </form>
    </div>
    <table id="data_table" class="my-3 table table-striped">
    <thead>
      <tr>
        <th>Project</th>
        <th>Spends {{ year }}</th>
        <th>Revenues {{ year }}</th>
        <th>Spends</th>
        <th>Revenues</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for project in query %}
          <tr>
            <td>{{ project.name }}</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>
              <div class="ms-auto px-2">
                    <a id='del_{{project.id}}'
                       href="{{url_for('receipt_blueprint.del_project', id_project=project.id)}}"
                       role="button" class="btn btn-outline-danger btn-sm">
                      <i class="bi bi-trash"></i></a>
                  </div>
            </td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/home-receipt/receipts_table.html
{% extends "base.html" %}
{% from "_formhelpers_add_product.html" import render_field %}
{% from "_formhelpers_update_receipt.html" import render_field_up %}

{% block content %}
<script>
    var databar = [{% for month, total in queryspends %}
        "{{total}}",
    {% endfor %}];
    var labelsbar = [{% for month, total in queryspends %}
        "{{month}}",
    {% endfor %}];
</script>

<div class="container">
    <div class="row p-3">
        <div class="col px-2">
            <canvas id="barchart"></canvas>
        </div>
    </div>
</div>
<script type="text/javascript" src="/static/barchart.js" language="javascript"></script>
  <table id="data_table_receipt" class="my-3 table table-striped">
    <thead>
      <tr>
        <th>Id</th>
        <th>Shop</th>
        <th>Price</th>
        <th>Date</th>
        <th>City</th>
        <th>Receipt</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for receipt, shop in query %}
          <tr>
            <td>{{ receipt.id }}</td>
            <td>{{ shop.name }}</td>
            <td>{{ receipt.total_price }}</td>
            <td>{{ receipt.date.strftime('%Y-%m-%d') }}</td>
            <td>Paris</td>
            <td>
              <a href="{{ url_for('receipt_blueprint.receipt_detail', id_receipt=receipt.id)}}"
                    class="btn btn-primary">
                <i class="mx-1 bi bi-zoom-in"></i> Receipt {{receipt.id}}
              </a></td>
            <td><a id="del_{{receipt.id}}" href="{{ url_for('receipt_blueprint.receipt_delete', id_receipt=receipt.id)}}"
            role="button" class="btn btn-outline-danger btn-sm">
              <i class="bi bi-trash"></i></a>

            </td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

app/templates/home-receipt/settings.html
{% extends "base.html" %}
{% from "_formhelpers_add_product.html" import render_field %}
{% from "_formhelpers_update_receipt.html" import render_field_up %}

{% block content %}
<div class="border p-2 rounded-1 m-2">
    <div class="border p-2 rounded-1 m-2">
        <form action="{{url_for('receipt_blueprint.settings')}}" method="post">
            <div class="row p-2 align-items-end">
                <h6>Exclude own personal information (phone, address, email)</h6>
                <div class="col-sm-4">
                    {{ render_field(form.address, class="form-control") }}
                </div>
                <div class="col-sm-2 ">
                    <button type="submit" class="my-2 btn btn-primary ">
                        <i class="bi p-1 bi-eyeglasses"></i>
                        exclude</button>
                </div>
            </div>
        </form>
    </div>
</div>
<table id="data_table" class="my-3 table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Address</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for address in addresses %}
          <tr>
            <td>{{ address.id }}</td>
            <td>{{ address.address }}</td>
            <td>
              <a href="{{url_for('receipt_blueprint.del_settings', id_address=address.id)}}"
                       role="button" class="btn btn-outline-danger btn-sm">
                      <i class="bi bi-x-circle"></i></a>
            </td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}